name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "honze-lhz.ip-ddns.com"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
# routes = [
#   { pattern = "docker.honze-lhz.ip-ddns.com", custom_domain = true },
#   { pattern = "quay.honze-lhz.ip-ddns.com", custom_domain = true },
#   { pattern = "gcr.honze-lhz.ip-ddns.com", custom_domain = true },
#   { pattern = "k8s-gcr.honze-lhz.ip-ddns.com", custom_domain = true },
#   { pattern = "k8s.honze-lhz.ip-ddns.com", custom_domain = true },
#   { pattern = "ghcr.honze-lhz.ip-ddns.com", custom_domain = true },
#   { pattern = "cloudsmith.honze-lhz.ip-ddns.com", custom_domain = true },
# ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.honze-lhz.ip-ddns.com", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
